default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= Rails.application.secrets.database_host %>
  database: <%= Rails.application.secrets.database %>
  username: <%= Rails.application.secrets.database_username %>
  password: <%= Rails.application.secrets.database_password %>

development:
  <<: *default
  database: lpc_server_development

test:
  <<: *default
  database: lpc_server_test

staging:
  <<: *default

production:
  <<: *default
