# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  database: <%= ENV["DEVELOPMENT_DATABASE"] %>
  database_host: <%= ENV["DEVELOPMENT_DATABASE_HOST"] %>
  database_username: <%= ENV["DEVELOPMENT_DATABASE_USERNAME"] %>
  database_password: <%= ENV["DEVELOPMENT_DATABSE_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  database: <%= ENV["TEST_DATABASE"] %>
  database_host: <%= ENV["TEST_DATABASE_HOST"] %>
  database_username: <%= ENV["TEST_DATABASE_USERNAME"] %>
  database_password: <%= ENV["TEST_DATABSE_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  database: <%= ENV["STAGING_DATABASE"] %>
  database_host: <%= ENV["STAGING_DATABASE_HOST"] %>
  database_username: <%= ENV["STAGING_DATABASE_USERNAME"] %>
  database_password: <%= ENV["STAGING_DATABASE_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
